spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:51289/app-db
        username: root
        password: secret
    jpa:
        hibernate:
            ddl-auto: create-drop
